on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:
jobs:
  build-custom-packages:
    name: Build Custom Packages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Prerequisites
      working-directory: custom/ghidra
      run: |
        sudo apt-get build-dep -y .
        sudo apt install -y wget
    - name: Download Ghidra
      working-directory: custom/ghidra
      run: ./get-ghidra.sh
    - name: Build Packages
      working-directory: custom/ghidra
      run: dpkg-buildpackage -b --no-sign
    - name: Upload Packages
      uses: actions/upload-artifact@v4
      with:
        name: ghidra-debian-package
        path: custom/ghidra*.deb
